kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  selector:
    project: expense
    tier: frontend
    app: frontend
  ports:
  - name: frontend-port
    protocol: TCP
    port: 80 # service port
    targetPort: 8080 # container port