configMap:
  db_host: expense-dev.ce7a44scwykd.us-east-1.rds.amazonaws.com
deployment:
  imageURL: 529088275803.dkr.ecr.us-east-1.amazonaws.com/expense/backend
  imageVersion: IMAGE_VERSION
hpa:
  cpuUtilization: 20