configMap:
  db_host: expense-dev.czn6yzxlcsiv.us-east-1.rds.amazonaws.com # mysql rds endpoint
deployment:
  imageURL: 315069654700.dkr.ecr.us-east-1.amazonaws.com/expense/dev/backend # backend ecr image id
  imageVersion: IMAGE_VERSION
hpa:
  cpuUtilization: 20